package:
  name: tifffile
  version: "0.6.2"

source:
  fn: tifffile-0.6.2.tar.gz
  url: https://pypi.python.org/packages/source/t/tifffile/tifffile-0.6.2.tar.gz
  md5: c36c66b1bc29f406f3277ad8e1d35d6d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tifffile = tifffile:main
    #
    # Would create an entry point called tifffile that calls tifffile.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python 2.7*|>=3.4
    - setuptools
    - numpy >=1.8.2

  run:
    - python 2.7*|>=3.4
    - numpy >=1.8.2

test:
  # Python imports
  imports:
    - tifffile

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/blink1073/tifffile
  license: BSD License
  summary: 'Read and write image data from and to TIFF files.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
