package:
  name: restview
  version: "2.4.0"

source:
  fn: restview-2.4.0.tar.gz
  url: https://pypi.python.org/packages/source/r/restview/restview-2.4.0.tar.gz
  md5: 5a1b5d90741097aaab8b0f168c3ba216
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - restview = restview:main
    #
    # Would create an entry point called restview that calls restview.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docutils
    - readme
    - pygments

  run:
    - python
    - docutils
    - readme
    - pygments

test:
  # Python imports
  imports:
    - restview

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mg.pov.lt/restview/
  license: GNU General Public License (GPL)
  summary: 'ReStructuredText viewer'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
