package:
  name: matplotlib
  version: 1.4.3

source:
  fn: matplotlib-1.4.3.tar.gz
  url: https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.4.3/matplotlib-1.4.3.tar.gz
  md5: 67a28a359af4919896d1ec74b6e6b3ce

  patches:
    - setupext.patch
    - cfg.patch
    - cfg_qt4agg.patch    [not osx]
    - rctmp_pyside.patch  [not osx]
    - osx-tk.patch        [osx]

requirements:
  build:
    - python
    - setuptools
    - numpy
    - python-dateutil
    - freetype
    - ffmpeg
    - nose
    - pyparsing
    - pytz
    - py2cairo            [linux and py2k]
    - tornado
    - libpng
    - zlib                [win]
    - pyqt
  run:
    - python
    - numpy
    - python-dateutil
    - freetype            [unix]
    - ffmpeg
    - pytz
    - pyparsing
    - py2cairo            [linux and py2k]
    - libpng              [unix]
    - pyqt

build:
  number: 5

about:
  home: http://matplotlib.sourceforge.net/
  license: PSF-based (http://matplotlib.sourceforge.net/users/license.html)
