package:
  name: readme
  version: "0.5.1"

source:
  fn: readme-0.5.1.tar.gz
  url: https://pypi.python.org/packages/source/r/readme/readme-0.5.1.tar.gz
  md5: a90568aac7ca8eb3f37a4f3c3f29accf
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - readme = readme:main
    #
    # Would create an entry point called readme that calls readme.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - bleach
    - docutils
    - pygments
    - six

  run:
    - python
    - setuptools
    - bleach
    - docutils
    - pygments
    - six

test:
  # Python imports
  imports:
    - readme
    - readme.integration

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pypa/readme
  license: Apache Software License
  summary: 'readme is a library for rendering "readme" descriptions for Warehouse'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
