package:
  name: codecov
  version: "1.4.0"

source:
  fn: codecov-1.4.0.tar.gz
  url: https://pypi.python.org/packages/source/c/codecov/codecov-1.4.0.tar.gz
  md5: df69aeebfa26305da3c2c1f01c1d70e3
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - codecov = codecov:main
    #
    # Would create an entry point called codecov that calls codecov.main()

    - codecov=codecov:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.0.0
    - coverage

  run:
    - python
    - requests >=2.0.0
    - coverage

test:
  # Python imports
  imports:
    - codecov

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - codecov --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - unittest2
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/codecov/codecov-python
  license: Apache Software License
  summary: 'Hosted coverage reports for Github, Bitbucket and Gitlab'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
